config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get '/search' => 'search#search'
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
     member do
       get :following, :followers
    end
  end
      resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :body, presence: true, length: {maximum: 200}
    has_many :favorites
    has_many :book_comments, dependent: :destroy
 def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
 end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,  :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image, destroy: false
  has_many :books
  validates :name, presence: true, length: {maximum: 10, minimum: 2}
  validates :introduction, length: {maximum: 50}
  has_many :favorites
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #フォロワー取得
  has_many :following_user, through: :follower, source: :followed #自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower #自分をフォローしている人
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
  
  include  JpPrefecture
  jp_prefecture :prefecture_code
  
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, except: [:top,:about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
    :email,
    :name,
    :postcode,
    :prefecture_name,
    :address_city,
    :address_street,
    :address_building
    ])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
    @book_comment = BookComment.find(params[:id])
    @book_comment.destroy
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: %i[edit update destroy]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @booknew = Book.new
    @book_comment = BookComment.new
  end

  def index
    @book = Book.all
    @user = current_user
    @booknew = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
    redirect_to books_path
    else render :show
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
   user = Book.find(params[:id]).user
   redirect_to books_path unless user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
   current_user.follow(params[:user_id])
   redirect_to request.referer
  end

  def destroy
   current_user.unfollow(params[:user_id])
   redirect_to request.referer
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how,@model,@value)
  end

  private
  def match(model,value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'User'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?","%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("name LIKE ?", "%#{value}%")
    end
  end

 def search_for(how, model, value)
  case how
     when 'match'
      match(model, value)
     when 'forward'
      forward(model,value)
     when 'backward'
      backward(model, value)
     when 'partical'
      partical(model, value)
  end
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      @books = @user.books
      render "edit"
    end
  end

  def following
    @following_users = current_user.following_user
  end

  def followers
    @followers_users = current_user.follower_user
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_bookcomments.html.erb
<% book.book_comments.each do |book_comment| %>
 <td>
   <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %><br >
   <%= book_comment.user.name %>
   <%= book_comment.comment %>
	　　<div>
     <% if book_comment.user == current_user %>
     <%= link_to "Destroy", book_book_comment_path(book_comment.book.id, book_comment.id), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
    </div>
     <% end %>
  <% end %>
 </td>

app/views/book_comments/create.js.erb
$(".comment").html("<%= j(render 'book_comments/bookcomments', book: @book) %>");
$("textarea").val("");

app/views/book_comments/destroy.js.erb
$(".comment").html("<%= j(render 'book_comments/bookcomments', book: @book_comment.book) %>");

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>
    <% if @book.errors.any? %>
		<div id="error_explanation">
			<h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @book.errors.full_messages.each do |book| %>
				<li><%= book %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
		<%= render "books/form", book: @book %>

		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

  <%= render 'layouts/footer' %>

app/views/books/index.html.erb
<div class='container'>
 <div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<% if @booknew.errors.any? %>
		<div id="error_explanation">
			<h3><%= @booknew.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @booknew.errors.full_messages.each do |book| %>
				<li><%= book %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @booknew %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @book.each do |book| %>
				<tr >
					 <td>
             <%= link_to user_path(book.user) do %>
             <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
             <% end %>
           </td>
           <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
           <td><%= book.body %></td>
					 <td class="favorite-btn_<%= book.id %>">
					   <%= render 'favorites/favorites', book: book %>
				   </td>
				   <td>
            <h6 class="comment-count">コメント数：<%= book.book_comments.count %></h6>
           </td>
				</tr>
			    <% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
 </div>
</div>

  <%= render 'layouts/footer' %>

app/views/books/show.html.erb
<div class='container'>
  <div class="row">
	<div class="col-xs-3">
      <h2>User info</h2>
	  <%= render 'users/profile' %>

	  <h2>New book</h2>
	  <%= render 'books/form', book: @booknew %>
    </div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@user) do %>
							<%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					    <% if current_user == @user %>
					<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					    <% end %>
					    <% if current_user == @user %>
					<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					    <% end %>
					<td class="favorite-btn_<%= @book.id %>">
			       <%= render 'favorites/favorites', book: @book %>
			    </td>
					<td>
						 <h6 class="comment-count">コメント数：<%= @book.book_comments.count %></h6>
					</td>
				</tr>
				<tr class="comment">
                  <%= render 'book_comments/bookcomments', book: @book %>
				</tr>
				<tr>
				 <td>
					 <%= form_with(model:[@book,@book_comment], data: {remote: true}) do |f| %>
                     <div class="row">
                       <div class="col-sm-24">
                        <%= f.text_area :comment, rows:'5', class: "form-control", id: "text" %>
                       </div>
                      </div>
                       <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
                     <% end %>
				 </td>
				</tr>
		</table>
    </div>
  </div>
</div>

  <%= render 'layouts/footer' %>

app/views/favorites/_favorites.html.erb
 <% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), class: :"glyphicon glyphicon-heart", method: :delete, remote: true do %>
   <% end %>
   <%= book.favorites.count %>
  <% else %>
   <%= link_to book_favorites_path(book), class: :"glyphicon glyphicon-heart", method: :post, remote: true do %>
  <% end %>
   <%= book.favorites.count %>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn_<%= @book.id %>").html("<%= j(render 'favorites/favorites', book: @book) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn_<%= @book.id %>").html("<%= j(render 'favorites/favorites', book: @book) %>");

app/views/homes/about.html.erb
<div class="container">
 <div class="row">
   <h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>
 </div>
</div>
    <%= render 'layouts/footer' %>

app/views/homes/top.html.erb
<div class="container">
 <div class="row">
  <div class='top-message col-xs-offset-3 col-xs-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>  !!</h1>
    <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>

  </div>
 </div>
</div>
    <%= render 'layouts/footer' %>

app/views/search/search.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @model == "user" %>
    <h2>Users search for '<%= @value %>'</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Introduction</th>
        </tr>
      </thead>
      <% @datas.each do |user| %>
       <tbody>
         <tr>
           <th>
             <%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40×40') %>
           </th>
           <th>
             <%= user.name %>
           </th>
           <th>
             <%= user.introduction %>
           </th>
         </tr>
       </tbody>
      <% end %>
      <% elsif @model == "book" %>
      <h2>Books search for '<%= @value %>'</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @datas.each do |book| %>
        <tbody>
          <tr>
            <th>
              <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40×40') %>
            </th>
            <th>
              <%= book.title %>
            </th>
            <th>
              <%= book.body %>
            </th>
          </tr>
        </tbody>
        <% end %>
      <% end %>
      </table>
    </table>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= @user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= @user.introduction %></th>
	</tr>

	<tr>
		<th>follows</th>
		<th><%= link_to @user.follower.count,following_user_path(@user) %></th>
	</tr>
	<tr>
		<th>followers</th>
		<th><%= link_to @user.followed.count, followers_user_path(@user) %></th>
	</tr>

	  <tr>
	  	<td><% if @user != current_user %>
           <% if current_user.following?(@user) %>
             <%= link_to 'フォローを外す', user_relationships_path(@user.id), class: 'btn-sm btn-primary', method: :delete %>
           <% else %>
             <%= link_to 'フォローする', user_relationships_path(@user.id), class: "btn-sm btn-success", method: :post %>
           <% end %>
         <% end %>
      </td>
    </tr>
</table>

<div class="row">
	<%= link_to '', edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
 <div class="row">

   <h2>User info</h2>

    <%= form_with model:@user, local: true do |f| %>

    	<!-- エラーメッセージ表示-->
	  <% if @user.errors.any? %>
		  <div id="error_explanation">
			  <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			  <ul>
				  <% @user.errors.full_messages.each do |user| %>
				  <li><%= user %></li>
				  <% end %>
			  </ul>
	      </div>
	  <% end %>
	    <!-- エラーメッセージ表示-->

	  <div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	  </div>

	  <div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	  </div>

	  <div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	  </div>

	  <div class="actions">
		<%= f.submit %>
	  </div>
    <% end %>
 </div>
</div>
    <%= render 'layouts/footer' %>

app/views/users/followers.html.erb
<div class='container'>
 <div class="row">
	 <div class="col-xs-9">
   <table class="table">
   <h2>Follower Users</h2>
   <thead>
    <tr>
			     <th>image</th>
			     <th>name</th>
		       <th colspan="3"></th>
		  </tr>
   </thead>
    <tbody>
     <tr>
        <% @followers_users.each do |followers_users| %>

        <td><%= attachment_image_tag(follower_users, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
        <td><%= follower_users.name %></td>
        <td><h6 class="comment-count">フォロー数：<%= follower_users.follower.count %></h6></td>
			  <td><h6 class="comment-count">フォロワー数：<%= follower_users.followed.count %></h6></td>
	  	  <td><%= link_to "Show", user_path(followers_user), class: "user_#{follower_users.id}" %></td>
     </tr>
        <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/users/following.html.erb
<div class='container'>
 <div class="row">
	 <div class="col-xs-9">
   <table class="table">
     <h2>Follows Users</h2>
      <thead>
		     <tr>
			     <th>image</th>
			     <th>name</th>
		       <th colspan="3"></th>
		     </tr>
	     </thead>
    <tbody>
     <tr>
        <% @following_users.each do |following_user| %>

        <td><%= attachment_image_tag(following_user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
        <td><%= following_user.name %></td>
        <td><h6 class="comment-count">フォロー数：<%= following_user.follower.count %></h6></td>
			     <td><h6 class="comment-count">フォロワー数：<%= following_user.followed.count %></h6></td>
	  	    <td><%= link_to "Show", user_path(following_user), class: "user_#{following_user.id}" %></td>
     </tr>
        <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<div class='container'>
 <div class="row">
	<div class="col-xs-3">
    <h2>User info</h2>
    <%= render 'users/profile', user: current_user %>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>
  </div>

    <div class="col-xs-9">
     <h2>Users</h2>
     <!--users一覧 -->
     <table class="table">
	     <thead>
		     <tr>
			     <th>image</th>
			     <th>name</th>
		       <th colspan="3"></th>
		     </tr>
	     </thead>

	     <tbody>
		     <% @users.each do |user| %>
		     <tr>
			     <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			     <td><%= user.name %></td>
			     <td><h6 class="comment-count">フォロー数：<%= user.follower.count %></h6></td>
			     <td><h6 class="comment-count">フォロワー数：<%= user.followed.count %></h6></td>
	  	     <td><% if user != current_user %>
                <% if current_user.following?(user) %>
                 <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete %>
                <% else %>
                 <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
                <% end %>
               <% end %>
          </td>
			     <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
		     </tr>
		     <% end %>
	    </tbody>
     </table>
<!--users一覧 -->
    </div>
 </div>
</div>

  <%= render 'layouts/footer' %>

app/views/users/show.html.erb
<div class='container'>
 <div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		
		<h2>New book</h2>
		<%= render 'books/form', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td>
				  	        <li>
                     <h6 class="comment-count">コメント数：<%= book.book_comments.count %></h6>
                    </li>
				    </td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
 </div>
</div>
   <%= render 'layouts/footer' %>